export const IPC = {
  CONFIG_GET: 'config:get',
  CONFIG_SAVE: 'config:save',
  CONFIG_CHANGED: 'config:changed',
  PACK_LIST: 'pack:list',
  PACK_SWITCH: 'pack:switch',
  PACK_SAVE_PERSONA: 'pack:save-persona',
  PACK_SAVE_CORPUS: 'pack:save-corpus',
  PACK_OPEN_DIR: 'pack:open-dir',
  PET_GET_STATE: 'pet:get-state',
  PET_EVENT: 'pet:event',
  PET_MOVE: 'pet:move',
  PET_DROP: 'pet:drop',
  PET_SET_CLICK_THROUGH: 'pet:set-click-through',
  PET_SET_SIZE: 'pet:set-size',
  PET_CONTEXT_MENU: 'pet:context-menu',
  PET_ALARM_SCHEDULE: 'pet:alarm-schedule',
  CHAT_SEND: 'chat:send',
  CHAT_TEST: 'chat:test',
  CHAT_GET_HISTORY: 'chat:get-history',
  TODO_RECOMMEND: 'todo:recommend',
  OBSIDIAN_GET_TODOS: 'obsidian:get-todos',
  OBSIDIAN_ADD_TODO: 'obsidian:add-todo',
  OBSIDIAN_COMPLETE_TODO: 'obsidian:complete-todo',
  WINDOW_OPEN_PANEL: 'window:open-panel',
  WINDOW_CLOSE_PANEL: 'window:close-panel',
  WINDOW_QUIT: 'window:quit'
} as const
